# name 必填，多实例运行时保证全局唯一
name = "mysql2starrocks"

[mysql]
host = "127.0.0.1"
port = 3306
username = "root"
password = ""

[starrocks]
host = "127.0.0.1"
port = 8040
username = "root"
password = ""

[[rule]]
source-schema = "mysql_test"
source-table = "tb1"
target-schema = "starrocks_test"
target-table = "tb1"

[[rule]]
source-schema = "mysql_test"
source-table = "tb2"
target-schema = "starrocks_test"
target-table = "tb2"