# name 必填，多实例运行时保证全局唯一
name = "mysql2starrocks"

[mysql]
host = "127.0.0.1"
port = 3306
username = "root"
password = ""

[starrocks]
host = "127.0.0.1"
port = 8040
username = "root"
password = ""

[sync-param]
# 同步chan队列最大值，达到会进行flush，最小100
channel-size = 10240
# 同步延迟秒数，达到会进行flush，最小1
flush-delay-second = 10

[[filter]]
type = "delete-dml-column"
[filter.config]
match-schema = "mysql_test"
match-table = "tb1"
columns = ["phone"]

[[rule]]
source-schema = "mysql_test"
source-table = "tb1"
target-schema = "starrocks_test"
target-table = "tb1"

[[rule]]
source-schema = "mysql_test"
source-table = "tb2"
target-schema = "starrocks_test"
target-table = "tb2"